<a href="https://colab.research.google.com/github/4060E051/python01/blob/master/20201007numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!git clone https://github.com/tensorflow/examples --depth 1

Cloning into 'examples'...
remote: Enumerating objects: 1861, done.
remote: Counting objects: 100% (1861/1861), done.
remote: Compressing objects: 100% (1170/1170), done.
remote: Total 1861 (delta 529), reused 1467 (delta 405), pack-reused 0
Receiving objects: 100% (1861/1861), 12.24 MiB | 7.70 MiB/s, done.
Resolving deltas: 100% (529/529), done.


In [ ]:
ls

examples/  sample_data/


In [ ]:
cd examples/

/content/examples


In [ ]:
ls

AUTHORS     CONTRIBUTING.md  LICENSE    setup.py
CODEOWNERS  courses/         lite/      templates/
community/  __init__.py      README.md  tensorflow_examples/


In [ ]:
import numpy as np
ar2=np.array([[0,2,5],[2,2,7]])
# ar2.shape
ar2.ndim

2

In [ ]:
ar=np.array([2,4,6,8,16]); 
ar.dtype

dtype('int64')

In [ ]:
import numpy as np
f_ar = np.array([13,-3,8.88])
f_ar

intf_ar=f_ar.astype(int)
intf_ar

array([13, -3,  8])

In [ ]:
import numpy as np

x3 = np.random.uniform(0,1,10)
x3

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [ ]:
import numpy as np
x = np.array([[1,2.0],[0,0],(1+1j,3.)])
x


array([[1.+0.j, 2.+0.j],
       [0.+0.j, 0.+0.j],
       [1.+1.j, 3.+0.j]])

In [ ]:
import numpy as np
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
import numpy as np
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
import numpy as np
np.linspace(1., 4., 7) # start, end, num

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [ ]:
import numpy as np
np.linspace(2.0, 3.0, num=3)

array([2. , 2.5, 3. ])

In [ ]:
import numpy as np
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [1]:
import numpy as np
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [2]:
import numpy as np
np.indices((3, 3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [3]:
import numpy as np
ar10=np.diag((2,1,4,6));
ar10

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [7]:
import numpy as np
a = np.array([0, 1, 2])
np.tile(a, 2)

array([0, 1, 2, 0, 1, 2])

In [6]:
import numpy as np
a = np.array([0, 1, 2])
np.tile(a, (2, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [5]:
import numpy as np
a = np.array([0, 1, 2])
np.tile(a, (2, 1, 2))

array([[[0, 1, 2, 0, 1, 2]],

       [[0, 1, 2, 0, 1, 2]]])

In [8]:
import numpy as np
np.tile(np.array([[1,2],[6,7]]),3)

array([[1, 2, 1, 2, 1, 2],
       [6, 7, 6, 7, 6, 7]])

In [9]:
import numpy as np
np.tile(np.array([[1,2],[6,7]]),(2,2))

array([[1, 2, 1, 2],
       [6, 7, 6, 7],
       [1, 2, 1, 2],
       [6, 7, 6, 7]])

In [10]:
import numpy as np
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [11]:
import numpy as np
np.tile(np.array([[1,2],[6,7]]),3)

array([[1, 2, 1, 2, 1, 2],
       [6, 7, 6, 7, 6, 7]])

In [12]:
import numpy as np
np.tile(np.array([[1,2],[6,7]]),(2,2))

array([[1, 2, 1, 2],
       [6, 7, 6, 7],
       [1, 2, 1, 2],
       [6, 7, 6, 7]])

NUMPY ndarray 運算
  1.reshape
  2.ravel()
  3.T
  4.newaxis

In [13]:
import numpy as np
x = np.arange(2,10).reshape(2,4)
x

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [14]:
import numpy as np
y = np.arange(2,10).reshape(4,2)
y

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [15]:
import numpy as np
ar=np.array([np.arange(1,6),np.arange(10,15)]); 
ar

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14]])

In [16]:
import numpy as np
ar=np.array([np.arange(1,6),np.arange(10,15)])
ar.ravel()

array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

In [17]:
import numpy as np
ar=np.array([np.arange(1,6),np.arange(10,15)])
ar.T

array([[ 1, 10],
       [ 2, 11],
       [ 3, 12],
       [ 4, 13],
       [ 5, 14]])

In [18]:
import numpy as np
ar=ar[:, np.newaxis]; ar.shape
ar

array([[[ 1,  2,  3,  4,  5]],

       [[10, 11, 12, 13, 14]]])

In [19]:
import numpy as np
ar=np.array([np.arange(1,6),np.arange(10,15)])
ar.T.ravel()

array([ 1, 10,  2, 11,  3, 12,  4, 13,  5, 14])

In [20]:
import numpy as np
ar=np.array([14,15,16])
ar=ar[:, np.newaxis]
ar.shape

(3, 1)

ndarray的索引(index)與切片運算(slice)

In [21]:
import numpy as np #索引(index)
x = np.arange(2,10)
# x
print(x[0])
print(x[-2])
print(x[-1])

2
8
9


In [22]:
import numpy as np
ar = np.array([[2,3,4],[9,8,7],[11,12,13]])
ar[1,2]

7

切片運算(slice)

In [36]:
import numpy as np
ar=2*np.arange(6)
# ar
ar[1:5:2]

array([2, 6])

In [37]:
import numpy as np
ar=2*np.arange(6)
# ar
ar[1:6:2]

array([ 2,  6, 10])

In [38]:
import numpy as np
ar=2*np.arange(6)
# ar
ar[:4]

array([0, 2, 4, 6])

測驗

In [23]:
import numpy as np
ar = np.array([[2,3,4],[9,8,7],[11,12,13]])
# ar
ar[:,1]  

array([ 3,  8, 12])

In [24]:
import numpy as np
ar = np.array([[2,3,4],[9,8,7],[11,12,13]])
# ar
ar[2,-1]

13

In [25]:
import numpy as np
ar=2*np.arange(6)
# ar
ar[::3]

array([0, 6])

In [26]:
import numpy as np
ar=2*np.arange(6)
# ar
ar[:3]=1
ar

array([ 1,  1,  1,  6,  8, 10])

In [27]:
import numpy as np
ar=2*np.arange(6)
# ar
ar[2:]=np.ones(4)
ar

array([0, 2, 1, 1, 1, 1])

ndarray的Reduction 運算:prod()|sum()|mean()|median()

In [29]:
import numpy as np
ar=np.arange(1,5)
ar.prod()


24

In [30]:
import numpy as np
ar=np.array([[2,3,4],[5,6,7],[8,9,10]])
ar.sum()

54

In [32]:
import numpy as np
ar=np.array([[2,3,4],[5,6,7],[8,9,10]])
ar.mean()

6.0

In [31]:
import numpy as np
ar=np.array([[2,3,4],[5,6,7],[8,9,10]])
np.median(ar)

6.0

In [34]:
import numpy as np

ar=np.array([np.arange(1,6),np.arange(1,6)])
# ar
np.prod(ar,axis=0)

array([ 1,  4,  9, 16, 25])

In [35]:
ar=np.array([np.arange(1,6),np.arange(1,6)])
# ar
np.prod(ar,axis=1)

array([120, 120])